name: Scraping run

on:
  schedule:
    - cron: '58 7 * * 1' # Every Monday between 7:00 and 8:00 UTC (exact time randomized by other workflow)
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run live scrape
        run: |
          python scrape.py wet
      - name: Add and commit new CSV
        uses: EndBug/add-and-commit@v9
        with:
          add: 'collected_results/'
          message: 'Add data from automated scraping run'
          pathspec_error_handling: exitImmediately
          push: true
