# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Scraping run (wet!)

on:
  workflow_dispatch
#  schedule:
#  - cron '0 17 * * 7' # Every Sunday at 19:00 CET

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run live scrape
      run: |
        python scrape.py wet
    - name: Add and commit new CSV
      uses: EndBug/add-and-commit@v9
      with:
        add: 'collected_results/'
        message: 'Added data from automated scraping run'
#        new_branch: new_data
        pathspec_error_handling: exitImmediately
        push: true
