name: Scraping run

on:
  schedule:
    - cron: '23 7 * * 1' # Every Monday between 7:00 and 8:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run live scrape
        run: |
          python scrape.py wet
      - name: Randomize workflow schedule
        run: |
          sed -i.bak "/^\s*- cron: '/{s/\([0-9]\+\)/$(shuf -i 0-59 -n 1)/}" .github/workflows/scrape.yml
      - name: Add and commit new CSV
        uses: EndBug/add-and-commit@v9
        with:
          add: 'collected_results/ .github/workflows/scrape.yml'
          message: 'Added data from automated scraping run'
          pathspec_error_handling: exitImmediately
          push: true
